services:
  apt-mirror:
    build: .
    image: mikepaxton/apt-mirror
    network_mode: bridge
    container_name: apt-mirror2
    environment:
      - TZ=America/Los_Angeles
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ${STORAGE_DIR}:/var/spool/apt-mirror
    ports:
      - 8140:80
    restart: unless-stopped
